export const trainerConstants = {
    //Action types for register
    REGISTER_REQUEST: 'TRAINER_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'TRAINER_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'TRAINER_REGISTER_FAILURE',

    //Action types for login
    LOGIN_REQUEST: 'TRAINER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'TRAINER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'TRAINER_LOGIN_FAILURE',
}